# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 18:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assets',
            name='asset_id',
        ),
    ]
