# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_remove_assets_asset_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='assets',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assets',
            name='maintenance_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
