# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 19:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20171115_1901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assets',
            old_name='location_id',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='assets',
            old_name='manufacturer_id',
            new_name='manufacturer',
        ),
    ]
