# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20171115_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='id',
            field=models.CharField(blank=True, editable=False, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
