# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 19:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_auto_20171120_1830'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assets',
            old_name='desc',
            new_name='description',
        ),
    ]
